z_filter:
  z_min: -0.025
  z_max: 2.0

xy_filter:
  enable: True
  x_min: -2.5
  x_max: 30.0
  y_min: -12.5
  y_max: 12.5

ground_segmentation:
  ground_segmentation_enable: True
  distance_threshold: 0.2
  ransac_n: 3
  num_iterations: 100

voxel_downsample:
  voxel_size: 0.025

statistical_outlier_removal:
  nb_neighbors: 5
  std_ratio: 0.01

patchwork_pp:
  enable: False
  verbose: True
  enable_RNR: False
  min_range: 0.0
  sensor_height: 0.0
  num_iter: 5
  th_seeds: 0.025
  th_dist: 0.05
  uprightness_thr: 0.5
  adaptive_seed_selection_margin: -0.05

dbscan_clustering:
  eps: 0.35
  min_samples: 10

bounding_box_type: "AABB" # "AABB" or "OBB"

detection_recording:
  enable: True
  save_dir: "data/ermis_detection/detection_res_2"