z_filter:
  z_filter_enable: True
  z_min: -0.05
  z_max: 2.0

ground_segmentation:
  ground_segmentation_enable: True
  distance_threshold: 0.2
  ransac_n: 3
  num_iterations: 100

voxel_downsample:
  voxel_size: 0.025

statistical_outlier_removal:
  nb_neighbors: 5
  std_ratio: 0.01

dbscan_clustering:
  eps: 0.35
  min_samples: 10

bounding_box_type: "AABB" # "AABB" or "OBB"